In [2]:
import os
from PIL import Image
import torch
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.models import load_model
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

In [3]:

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

test_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

test_generator = test_datagen.flow_from_directory(
    r"C:\Users\KristianHaltenJensen\Noroff\Bachelor\final test",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False 
)

Found 59 images belonging to 12 classes.


In [5]:
model = load_model("ResNet50_WPD.keras")

pred_probs = model.predict(test_generator)
y_pred = np.argmax(pred_probs, axis=1)

y_true = test_generator.classes
class_names = list(test_generator.class_indices.keys())
accuracy = np.mean(y_pred == y_true)
print(f"Accuracy: {accuracy:.4f}")


print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))


C:\Users\KristianHaltenJensen\anaconda4\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


2/2 ━━━━━━━━━━━━━━━━━━━━ 7s 3s/step
Accuracy: 0.3390

Classification Report:
              precision    recall  f1-score   support

  Black Rust       0.50      0.40      0.44         5
       Blast       0.83      1.00      0.91         5
  Brown Rust       0.67      0.80      0.73         5
 Head Blight       0.00      0.00      0.00         5
     Healthy       0.00      0.00      0.00         5
 Leaf Blight       0.00      0.00      0.00         4
      Mildew       0.00      0.00      0.00         5
    Root Rot       0.00      0.00      0.00         5
    Septoria       0.00      0.00      0.00         5
        Smut       1.00      1.00      1.00         5
    Tan Spot       0.31      0.80      0.44         5
 Yellow Rust       0.00      0.00      0.00         5

    accuracy                           0.34        59
   macro avg       0.28      0.33      0.29        59
weighted avg       0.28      0.34      0.30        59



C:\Users\KristianHaltenJensen\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\KristianHaltenJensen\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\KristianHaltenJensen\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred))


Confusion Matrix:
[[2 0 1 0 0 0 1 0 0 0 1 0]
 [0 5 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 1]
 [0 3 0 0 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 3 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 2 1]
 [0 0 0 0 0 0 0 4 0 0 1 0]
 [0 1 0 3 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 1 0 0 0 4 0]
 [1 1 2 0 0 0 0 0 0 0 1 0]]
