In [1]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.resnet50 import preprocess_input
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score




In [ ]:
TEST_DIR = r"C:\Users\KristianHaltenJensen\Noroff\Bachelor\LWDCD final test"
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

MODEL_PATH = "ResNet50_finetuned_LWDCD.keras"  


In [2]:
test_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)

print("\nClass indices:")
print(test_generator.class_indices)


Found 45 images belonging to 3 classes.

Class indices:
{'Healthy Wheat': 0, 'Leaf Rust': 1, 'Wheat Loose Smut': 2}


In [3]:
model = load_model(MODEL_PATH)

In [5]:
test_loss, test_acc = model.evaluate(test_generator, verbose=1)
print(f"\nTest Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_acc:.4f}")

pred_probs = model.predict(test_generator, verbose=1)
y_pred = np.argmax(pred_probs, axis=1)
y_true = test_generator.classes
class_names = list(test_generator.class_indices.keys())

print("\nAccuracy Score:")
print(f"{accuracy_score(y_true, y_pred):.4f}")

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred))


2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 304ms/step - accuracy: 0.7981 - loss: 1.5351

Test Loss: 1.3523
Test Accuracy: 0.8222
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 359ms/step

Accuracy Score:
0.8222

Classification Report:
                  precision    recall  f1-score   support

   Healthy Wheat       1.00      0.47      0.64        15
       Leaf Rust       0.65      1.00      0.79        15
Wheat Loose Smut       1.00      1.00      1.00        15

        accuracy                           0.82        45
       macro avg       0.88      0.82      0.81        45
    weighted avg       0.88      0.82      0.81        45


Confusion Matrix:
[[ 7  8  0]
 [ 0 15  0]
 [ 0  0 15]]
