In [2]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


Found 45 images belonging to 3 classes.


C:\Users\KristianHaltenJensen\anaconda4\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 192ms/step
Accuracy: 0.7111111111111111
                  precision    recall  f1-score   support

   Healthy Wheat       0.83      0.33      0.48        15
       Leaf Rust       0.68      0.87      0.76        15
Wheat Loose Smut       0.70      0.93      0.80        15

        accuracy                           0.71        45
       macro avg       0.74      0.71      0.68        45
    weighted avg       0.74      0.71      0.68        45

[[ 5  5  5]
 [ 1 13  1]
 [ 0  1 14]]


In [ ]:

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
TEST_DIR = r"C:\Users\KristianHaltenJensen\Noroff\Bachelor\LWDCD final test"

test_datagen = ImageDataGenerator(rescale=1.0 / 255.0)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)

model = load_model("WheatNetwork_LWDCD.keras")

pred_probs = model.predict(test_generator)
y_pred = np.argmax(pred_probs, axis=1)
y_true = test_generator.classes
class_names = list(test_generator.class_indices.keys())

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred, target_names=class_names))
print(confusion_matrix(y_true, y_pred))